=== dackmin/gba-studio/public/templates/commons/.schemas/scene.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "scene.json",
  "definitions": {
    "CharacterDirection": {
      "enum": [
        "down",
        "left",
        "right",
        "up"
      ],
      "type": "string"
    },
    "Actor": {
      "type": "object",
      "properties": {
        "type": {
          "const": "actor",
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "x": {
          "type": "number"
        },
        "y": {
          "type": "number"
        },
        "z": {
          "type": "number"
        },
        "width": {
          "type": "number"
        },
        "height": {
          "type": "number"
        },
        "direction": {
          "$ref": "#/definitions/CharacterDirection"
        },
        "sprite": {
          "type": "string"
        },
        "disableDirectionOnInteract": {
          "type": "boolean"
        },
        "collisionGroup": {
          "maximum": 4,
          "minimum": 0,
          "type": "number"
        },
        "events": {
          "additionalProperties": false,
          "properties": {
            "collide": {
              "type": "array",
              "items": {
                "$ref": "event.json#/definitions/Event"
              }
            },
            "interact": {
              "type": "array",
              "items": {
                "$ref": "event.json#/definitions/Event"
              }
            },
            "init": {
              "type": "array",
              "items": {
                "$ref": "event.json#/definitions/Event"
              }
            },
            "update": {
              "type": "array",
              "items": {
                "$ref": "event.json#/definitions/Event"
              }
            }
          },
          "type": "object"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "type",
        "name",
        "x",
        "y",
        "sprite"
      ]
    },
    "Sensor": {
      "type": "object",
      "properties": {
        "type": {
          "const": "sensor",
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "x": {
          "type": "number"
        },
        "y": {
          "type": "number"
        },
        "width": {
          "type": "number"
        },
        "height": {
          "type": "number"
        },
        "events": {
          "additionalProperties": false,
          "properties": {
            "enter": {
              "type": "array",
              "items": {
                "$ref": "event.json#/definitions/Event"
              }
            },
            "interact": {
              "type": "array",
              "items": {
                "$ref": "event.json#/definitions/Event"
              }
            },
            "leave": {
              "type": "array",
              "items": {
                "$ref": "event.json#/definitions/Event"
              }
            }
          },
          "type": "object"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "type",
        "name",
        "x",
        "y",
        "width",
        "height"
      ]
    },
    "Sprite": {
      "type": "object",
      "properties": {
        "type": {
          "const": "sprite",
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "sprite": {
          "type": "string"
        },
        "width": {
          "type": "number"
        },
        "height": {
          "type": "number"
        },
        "x": {
          "type": "number"
        },
        "y": {
          "type": "number"
        },
        "z": {
          "type": "number"
        },
        "collisionGroup": {
          "maximum": 4,
          "minimum": 0,
          "type": "number"
        },
        "events": {
          "additionalProperties": false,
          "properties": {
            "collide": {
              "type": "array",
              "items": {
                "$ref": "event.json#/definitions/Event"
              }
            },
            "init": {
              "type": "array",
              "items": {
                "$ref": "event.json#/definitions/Event"
              }
            },
            "interact": {
              "type": "array",
              "items": {
                "$ref": "event.json#/definitions/Event"
              }
            }
          },
          "type": "object"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "type",
        "name",
        "sprite",
        "x",
        "y"
      ]
    },
    "Player": {
      "type": "object",
      "properties": {
        "type": {
          "const": "player",
          "type": "string"
        },
        "x": {
          "type": "number"
        },
        "y": {
          "type": "number"
        },
        "z": {
          "type": "number"
        },
        "width": {
          "type": "number"
        },
        "height": {
          "type": "number"
        },
        "direction": {
          "$ref": "#/definitions/CharacterDirection"
        },
        "sprite": {
          "type": "string"
        },
        "collisionGroup": {
          "maximum": 4,
          "minimum": 0,
          "type": "number"
        }
      },
      "required": [
        "x",
        "y"
      ]
    },
    "Scene": {
      "properties": {
        "$schema": {
          "type": "string"
        },
        "sceneType": {
          "enum": ["logos", "2d-top-down", "side-scroller"],
          "type": "string"
        },
        "background": {
          "type": "string"
        },
        "events": {
          "items": {
            "$ref": "event.json#/definitions/Event"
          },
          "type": "array"
        },
        "name": {
          "type": "string"
        },
        "player": {
          "$ref": "#/definitions/Player"
        },
        "actors": {
          "type": "array",
          "items": { "$ref": "#/definitions/Actor" }
        },
        "sprites": {
          "type": "array",
          "items": { "$ref": "#/definitions/Sprite" }
        },
        "hud": {
          "type": "string"
        },
        "map": {
          "$ref": "#/definitions/Map"
        },
        "type": {
          "const": "scene",
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "required": [
        "$schema",
        "type",
        "sceneType",
        "name"
      ],
      "type": "object"
    },
    "Map": {
      "type": "object",
      "properties": {
        "type": {
          "const": "map",
          "type": "string"
        },
        "scene": {
          "type": "string"
        },
        "gridSize": {
          "type": "number"
        },
        "width": {
          "type": "number"
        },
        "height": {
          "type": "number"
        },
        "collisions": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "sensors": {
          "type": "array",
          "items": { "$ref": "#/definitions/Sensor" }
        }
      },
      "required": [
        "type",
        "gridSize",
        "width",
        "height"
      ]
    }
  },
  "$ref": "#/definitions/Scene"
}

=== dackmin/gba-studio/public/templates/2d-sample/content/scene_0.json
{
  "$schema": "https://raw.githubusercontent.com/dackmin/gba-studio/main/public/templates/commons/.schemas/scene.json",
  "type": "scene",
  "sceneType": "2d-top-down",
  "name": "Scene 0",
  "background": "bg_default",
  "events": [{
    "type": "show-dialog",
    "text": "Welcome to the game!"
  }, {
    "type": "wait-for-button",
    "buttons": ["Start"]
  }]
}

=== dackmin/gba-studio/tests/fixtures/basic-game/content/scene_4.json
{
  "id": "e6b9f8a1-4c58-4799-8a40-16eda41dda41",
  "name": "Side Scroller",
  "background": "95458cca-f5fb-49e0-ab08-3e24a77c7703",
  "type": "scene",
  "sceneType": "side-scroller",
  "player": {
    "type": "player",
    "x": 3,
    "y": 4
  },
  "events": [
    {
      "type": "fade-in",
      "duration": 200,
      "id": "cd5f6cca-61c5-4cf2-ba9e-e37edc8df4c5"
    }
  ],
  "map": {
    "type": "map",
    "gridSize": 16,
    "width": 64,
    "height": 32,
    "collisions": [
      "2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0",
      "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0",
      "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0",
      "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0",
      "0,0,0,0,0,0,0,0,0,0,0,3,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0",
      "1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1",
      "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0",
      "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0",
      "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0",
      "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0",
      "0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0",
      "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0",
      "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0",
      "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0",
      "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0",
      "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0",
      "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0",
      "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0",
      "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0",
      "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0",
      "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0",
      "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0",
      "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0",
      "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0",
      "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0",
      "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0",
      "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0",
      "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0",
      "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0",
      "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0",
      "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0",
      "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"
    ]
  },
  "$schema": "https://raw.githubusercontent.com/dackmin/gba-studio/main/public/templates/commons/.schemas/scene.json"
}
