=== dackmin/gba-studio/public/templates/commons/.schemas/script.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "script.json",
  "definitions": {
    "Script": {
      "additionalProperties": false,
      "properties": {
        "$schema": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "type": {
          "const": "script",
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "parameters": {
          "type": "array",
          "maxItems": 10,
          "items": {
            "type": "object",
            "additionalProperties": false,
            "required": ["id", "name", "type"],
            "properties": {
              "id": { "type": "string" },
              "name": { "type": "string" },
              "type": { "enum": ["value", "variable", "actor"], "type": "string" }
            }
          }
        },
        "events": {
          "items": {
            "$ref": "event.json#/definitions/Event"
          },
          "type": "array"
        }
      },
      "required": [
        "$schema",
        "type",
        "name"
      ]
    }
  },
  "$ref": "#/definitions/Script"
}

=== dackmin/gba-studio/tests/fixtures/basic-game/content/script_0.json
{
  "id": "0db1c374-9a85-4e15-b816-631039d765f6",
  "type": "script",
  "name": "Actor Dialogs",
  "events": [
    {
      "type": "move-actor-to",
      "actor": "__script_param_74cdc1b4-da05-4b51-9f20-6dc15dde4814",
      "x": 0,
      "y": 0
    }
  ],
  "parameters": [
    {
      "id": "74cdc1b4-da05-4b51-9f20-6dc15dde4814",
      "name": "Actor",
      "type": "actor"
    }
  ],
  "$schema": "https://raw.githubusercontent.com/dackmin/gba-studio/main/public/templates/commons/.schemas/script.json"
}
